name: Run auto download
on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:
        inputs:
            prev:
                description: 'Get previous firmware versions (if available) instead of latest.'
                required: false
                default: false
                type: boolean
            manufacturers:
                description: 'Only trigger updates for given manufacturers (CSV, no space).'
                required: false
                default: ''
                type: string
            ignore_cache:
                description: 'Ignore cached data in .cache for this run.'
                required: false
                default: false
                type: boolean

permissions:
    contents: write

jobs:
    run-autodl:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - uses: pnpm/action-setup@v4

            - uses: actions/setup-node@v5
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            - name: Install dependencies
              run: pnpm i --frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Run Autodl
              uses: actions/github-script@v8
              env:
                  NODE_EXTRA_CA_CERTS: cacerts.pem
                  PREV: ${{ inputs.prev == 'true' && '1' || '' }}
                  IGNORE_CACHE: ${{ inputs.ignore_cache == 'true' && '1' || '' }}
              with:
                  script: |
                      const {runAutodl} = await import("${{ github.workspace }}/dist/ghw_run_autodl.js")

                      await runAutodl(github, core, context, "${{ inputs.manufacturers || '' }}")

                      const {identifyStacks} = await import("${{ github.workspace }}/dist/ghw_identify_stacks.js")

                      identifyStacks(github, core, context)

            - name: Create Autodl release
              uses: actions/github-script@v8
              with:
                  script: |
                      const {createAutodlRelease} = await import("${{ github.workspace }}/dist/ghw_create_autodl_release.js")

                      await createAutodlRelease(github, core, context)

            - name: Commit changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m "Autodl update" || echo 'Nothing to commit'
                  git push
